{
 "title": "SIEM Buffer",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "aps_siem_requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_task_operator_aps_siem_requests) by (task_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "aps_siem_ip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_task_operator_aps_siem_ip) by (task_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "aps_siem_counter",
   "type": "timeseries",
   "description": "Number of times the Mapper is called.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(flink_taskmanager_job_task_operator_aps_siem_counter[45s])) by (task_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "aps_siem_ip_buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_task_operator_aps_siem_ip_buffer) by (task_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ip_aps_siem_ip_topn",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_ts_ip_aps_siem_ip_topn) by (ip) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ip_aps_siem_ip_topn",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 8 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_ts_ip_aps_siem_ip_topn) by (task_id)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}